### ISSUE TITLE
Error while restoring session

### ISSUE THREAD

**Issue by MhankBarBar** [harianjalundu77/wamd#1]
Sorry in advance, I don't really understand python, but I'm trying to save the session and then restore it again

My code is like this
```python
from os import path
from wamd.common import AuthState

@inlineCallbacks
def onConnect(connection):
    print("\nConnection 1: %r" % (connection, ))
    # check if session path if exists
    # and restore the session
    if path.exists("session.json"):
        session = eval(open("session.json").read())
        connection.authState = AuthState.fromJson(session)
    else:
        connection.on("qr", handleQr)

    # the new connection after successfull authentication
    # will be different than provided the first connection
    # since the connection will automatically be restarted
    # after authentication.
    connection = yield connection.authenticate()

    # check if session file not in path
    # and save session to file
    if not path.exists("session.json"):
        open("session.json","w").write(str(connection.authState.toJson()))
    connection.on("inbox", inboxReceiver)
    print("\nConnection 2: %r" % (connection, ))
```

but it fails and can't restore session

**Comment by serenity-77** [comment]
Is there any exception or failure printed on the screen?

**Comment by MhankBarBar** [comment]
Sorry, I've been able to save and then restore it again, this issued solve when I store session in MultiDeviceWhatsAppClientProtocol

But showing error like this
![Screenshot_2021-11-17-21-48-29-80](https://user-images.githubusercontent.com/55822959/142222953-746e90d1-4e0f-4d33-9c2e-48ced6edec73.jpg)

**Comment by serenity-77** [comment]
sepertinya masalah pada saat decrypt  pesan masuk
sedang di lakukan perbaikan.

**Comment by MhankBarBar** [comment]
Gimana cara handle event new message setelah restore session?

**Comment by a5r0n** [comment]
u need to restore the auth_state before u run the reactor. (e.g in the factory function)

something like:
``` python
def protocol_factory():
    # Do any initialization here, such as reading session file
    # to be supplied to the protocol/connection.
    if path.exists("auth.json"):
        with open("auth.json") as f:
            print("Loading auth state from auth.json")
            auth_state = AuthState.fromJson(json.loads(f.read()))
    else:
        auth_state = AuthState()

    return MultiDeviceWhatsAppClient(authState=auth_state)

```

**Comment by MhankBarBar** [comment]
> u need to restore the auth_state before u run the reactor. (e.g in the factory function)
> 
> something like:
> 
> ```python
> def protocol_factory():
>     # Do any initialization here, such as reading session file
>     # to be supplied to the protocol/connection.
>     if path.exists("auth.json"):
>         with open("auth.json") as f:
>             print("Loading auth state from auth.json")
>             auth_state = AuthState.fromJson(json.loads(f.read()))
>     else:
>         auth_state = AuthState()
> 
>     return MultiDeviceWhatsAppClient(authState=auth_state)
> ```
I've been trying this for a long time, but still can't handle events
