### ISSUE TITLE
Integration Flask or Django

### ISSUE THREAD

**Issue by syifarahmat** [harianjalundu77/wamd#5]
Any examples for integrating with Flask or Django?
Or example execute relayMessage from rest api

🙏🙏

**Comment by serenity-77** [comment]
there is no example to that for now
but you can use [Twisted Web](https://docs.twistedmatrix.com/en/twisted-18.9.0/web/howto/using-twistedweb.html)

Start the twisted web server along with the wamd client

**Comment by syifarahmat** [comment]
> there is no example to that for now but you can use [Twisted Web](https://docs.twistedmatrix.com/en/twisted-18.9.0/web/howto/using-twistedweb.html)
> 
> Start the twisted web server along with the wamd client

Ok thank's
